no change     /n/app/miniconda3/23.1.0/condabin/conda
no change     /n/app/miniconda3/23.1.0/bin/conda
no change     /n/app/miniconda3/23.1.0/bin/conda-env
no change     /n/app/miniconda3/23.1.0/bin/activate
no change     /n/app/miniconda3/23.1.0/bin/deactivate
no change     /n/app/miniconda3/23.1.0/etc/profile.d/conda.sh
no change     /n/app/miniconda3/23.1.0/etc/fish/conf.d/conda.fish
no change     /n/app/miniconda3/23.1.0/shell/condabin/Conda.psm1
no change     /n/app/miniconda3/23.1.0/shell/condabin/conda-hook.ps1
no change     /n/app/miniconda3/23.1.0/lib/python3.10/site-packages/xontrib/conda.xsh
no change     /n/app/miniconda3/23.1.0/etc/profile.d/conda.csh
no change     /home/kel331/.bashrc
No action taken.
4.constructCCI.py:10: DtypeWarning: Columns (4,5,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f, sep="\t")
Number of output files to parse: 1
    id_cp_interaction  ... visceromotor neuron|visceromotor neuron
0     CPI-SC0A2DB962D  ...                                     1.0
1     CPI-SC0B5CEA47D  ...                                     1.0
2     CPI-SC0B86B7CED  ...                                     1.0
3     CPI-SC0FA343CEF  ...                                     1.0
4     CPI-SC0CCCF9A7F  ...                                     1.0
..                ...  ...                                     ...
763   CPI-SS0291D3D2E  ...                                     1.0
764   CPI-CS09A35DD21  ...                                     1.0
765   CPI-SS096F8C268  ...                                     1.0
766   CPI-SS0ABEE4D3D  ...                                     1.0
767   CPI-SS07D508428  ...                                     1.0

[768 rows x 211613 columns]
Traceback (most recent call last):
  File "4.constructCCI.py", line 67, in <module>
    main() 
  File "4.constructCCI.py", line 60, in main
    cci = generate_cci(cpdb_files)
  File "4.constructCCI.py", line 46, in generate_cci
    cluster_adj = parse_cpdb_output(f, cluster_adj, pvalue, cutoff)
  File "4.constructCCI.py", line 12, in parse_cpdb_output
    for col in df.iteritems():
  File "/home/kel331/.conda/envs/pinnacle/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'iteritems'
